### ISSUE TITLE
Write custom queries like we do for sql?

### ISSUE THREAD

**Issue by haroonKhan-10p** [db-migrate/mongodb#23]

**Comment by haroonKhan-10p** [comment]
tester.10p@test.com

**Comment by haroonKhan-10p** [comment]
I totally love the counter part of this package which is mysql. I just want to know if we can write custom queries like we do with mysql in .sql files?

**Comment by wzrdtales** [comment]
@BorntraegerMarc just recently added a method to access the driver directly. See https://github.com/db-migrate/mongodb/pull/21

Since NoSQL databases like mongodb have no common way to send them queries of any kind this is kinda specific to the db and it depends if they have like cassandra their own dialect or if they do not have any at all. The access to the underlying driver directly will however solve the problem for you as well.
